version: '3'
services:
  qaci-node:
    tty: true
    image: qaci-node:v0.5
    ports:
      - '8080:8080'
    depends_on:
      - mongo
    environment:
      mongo_host: mongo
      mongo_user: qaci-coordinator
      mongo_pass: let-me-in
      mongo_db: qaci-db
      mongo_uri: 'mongodb://qaci-coordinator:let-me-in@host.docker.internal'
      ETH_PROVIDER: 'http://127.0.0.1:8545'
    volumes:
      - ~/maci:/root/dev-maci
      - ~/maci_v0_10:/root/dev-maci_v0_10
      - ~/maci/cli/zkeys:/root/maci/cli/zkeys
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: qaci-coordinator
      MONGO_INITDB_ROOT_PASSWORD: let-me-in
    volumes:
      - ./data/mongodb:/data/db
